version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: henry
      POSTGRES_PASSWORD: henry
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 15432:5432